---
- name: "Playing with Ansible and Git"
  hosts: all
  tasks:

    - name: Set Variable github_pat
      ansible.builtin.set_fact:
        github_pat: "{{ lookup('ansible.builtin.env', 'GITHUB_PAT') }}"

    - name: End the Play
      when: github_pat | length == 0
      block:
        - name: Message
          ansible.builtin.debug:
            msg: "You need to set the Env Variable GITHUB_PAT"
        - name: Meta End Play
          ansible.builtin.meta: end_play

    - name: Print debug infos
      ansible.builtin.debug:
        msg:
          - "Repository: {{ name }} - Default Branch: {{ default_branch }}"

    - name: Get Protected Branch Settings
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ owner.login }}/{{ name }}/branches/{{ default_branch }}/protection"
        headers:
          Authorization: "Token {{ github_pat }}"
        use_netrc: false
      register: branch_protection_settings
      ignore_errors: true

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ branch_protection_settings }}"
